version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: root
      DB_NAME: nestjs_db
    volumes:
      - .:/app
      - /app/node_modules 
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - nest-app
    command: npm run start:dev


  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs_db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    healthcheck:
      test: mysql sys --user=root --password='root' --silent --execute "SELECT 1;"
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nest-app

networks:
  nest-app:
    driver: bridge

